---
title: "Untitled"
author: "AGBLODOE Komi /  SALMANI Soheil  M2 SSD"
date: "10 janvier 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r label = "Submission - dependencies", include = FALSE}

if ( !exists(x = "params") ) {
    params                      <- NULL
}
if ( is.null(x = params$package_repository) ) {
    params$package_repository   <- "https://cloud.r-project.org"
}
if ( is.null(x = params$install_dependencies) ) {
    params$install_dependencies <- TRUE
}
print(params)
if ( params$install_dependencies ) {
    installed_packages <- installed.packages( )
    for (package in c("zip") ) {
        if ( !{ package %in% installed_packages } ) {
            print(x = paste("Installation of ", package, sep = "") )
            install.packages(
                pkgs = package
              , repos = params$package_repository
            )
        } else {
            print(x = paste(package, " is installed.", sep = "") )
        }
    } 
    remove(list = c("installed_packages", "package") ) 
}

```

```{r}
program <- function(input_learn, input_test) {
    ##
    ## YOUR CODE BEGINS HERE
    ##
    
    for ( v in c("sex", "tissue_status", "histology", "dead", "dead_at_24_months", "t", "n", "m", "tnm_stage") ) {
        input_learn[[ v ]] <- as.factor(x = input_learn[[ v ]])
    }
    ## summary(object = input_learn)

    ## We remove constant variables :
    idx <- apply(
        X      = input_learn,
        MARGIN = 2,
        FUN    = function(x) {
            length(x = table(x = x) ) > 1
        } )
    input_learn   <- input_learn[ , idx, drop = FALSE]

    ##
    ## YOUR CODE BEGINS HERE
    ##

    input_learn$os_months <- NULL
    input_learn$dead      <- NULL
    model <- glm(
        formula = dead_at_24_months ~ . ## sex + histology + t + n + m + tnm_stage
      , data    = input_learn
      , family  = binomial(link = 'logit')
    )
    ## summary(object = model)

    virulence_levels <- levels(x = input_learn$dead_at_24_months)

    pred <- predict.glm(object = model, newdata = input_test, type = "response")

    idx  <- pred <= 0.5
    pred[  idx ] <- virulence_levels[ 1 ]
    pred[ !idx ] <- virulence_levels[ 2 ]
    table(pred, useNA = "ifany")
    
    return( pred )
       
    ##
    ## YOUR CODE ENDS HERE
    ##
}

```

```{r}
## DO NOT CHANGE THE FOLLOWING CODE
    ##

    data_learn <- readRDS(file = "data_learn.rds") 

    ## we use the previously defined function 'program' to estimate A :
    res <- program(
        input_learn  = data_learn
         ,input_test = data_learn ## we re-use 'data_learn' only for test purpose
    )
    attach(data_learn) 
```

```{r}
gs = names(data_learn)[13:1012]
p_values = rep(NA, length(gs)) 
names(p_values) <- gs
 

d<-data_learn[!is.na(data_learn$dead_at_24_months),]
d$dead_at_24_months <- as.numeric(d$dead_at_24_months == "true")

for (i in 1:length(gs)) {
  model <- glm( 
    formula = dead_at_24_months ~ d[, gs[i]],
    data = d,
    family = binomial(link = 'logit')
  )
   
  coeffs = summary(model)$coefficient
  if (nrow(coeffs) != 1) {
    p_values[i] = summary(model)$coefficient[2, 4]
  } 
} 
 
summary(model) 

p_values_min = head(sort(p_values), n = 15)
genes_selected = paste(names(p_values_min), collapse = "+", sep = "")
form = paste("dead_at_24_months ~", genes_selected)

input_learn$os_months <- NULL
    input_learn$dead      <- NULL
    model <- glm(
        formula = as.formula(form)
      , data    = d
      , family  = binomial(link = 'logit') 
    ) 
    ## summary(object = model)

    virulence_levels <- c(0,1) #levels(x = d$dead_at_24_months)

    pred <- predict.glm(object = model, newdata = d, type = "response")

    idx  <- pred <= 0.5
    pred[  idx ] <- virulence_levels[ 1 ]
    pred[ !idx ] <- virulence_levels[ 2 ]
    table(pred, useNA = "ifany")
    
    return( pred )
```

Sélection de variables
```{r}
form = paste("dead_at_24_months ~", genes_selected)

model <- glm(
  formula = as.formula(form),
  data = d,
  family = binomial(link = 'logit')
)
step(model, dir = "backward")

virulence_levels <- c(0,1) #levels(x = d$dead_at_24_months)

pred <- predict.glm(object = model, newdata = d, type = "response")
idx  <- pred <= 0.5
pred[  idx ] <- virulence_levels[ 1 ]
pred[ !idx ] <- virulence_levels[ 2 ] 
table(pred, useNA = "ifany")
```

```{r}
model <- glm(
  formula = dead_at_24_months~ SBK3 + ENTPD2 + ZNF654 + ADAM10 + sex + histology + t,
  data = d,
  family = binomial(link = 'logit')
)

step(model, dir = "backward")

virulence_levels <- c(0,1) #levels(x = d$dead_at_24_months)

pred <- predict.glm(object = model, newdata = d, type = "response")
idx  <- pred <= 0.5
pred[  idx ] <- virulence_levels[ 1 ]
pred[ !idx ] <- virulence_levels[ 2 ] 
table(pred, useNA = "ifany") 

```

```{r label = "Submission - program zip file", echo = TRUE, results = "verbatim"}

## we save the source code as a R file named 'program.R' :
dump(
    list = c("program")
  , file = "program.R"
)
## we also generate the 'metadata' file
cat(
    "command: Rscript $program/program.R $input $output"
  , file = "metadata"
)

## we create the associated zip file :
zip_program <- paste0("program_", format(x = Sys.time( ), format = "%Y_%m_%d_%S"), ".zip")
zip::zipr(
         zipfile = zip_program
       , files   = c("program.R", "metadata")
     )
print(x = zip_program)  
```

