Please use the `submission_script_sex.Rmd` contained in the `starting_kit` folder as a template to write, run and save your code.

## Prediction of the patient sex

```{r echo=TRUE, results="verbnatim", label="generate_zip_file"}
### DO NOT CHANGE THIS PART
d <- readRDS("data_learn.rds")
for ( v in c("sex", "tissue_status", "histology", "os_months", "dead", "dead_at_24_months", "t", "n", "m", "tnm_stage", "tnm_grade") ) {
    d[[ v ]] <- as.factor(x = d[[ v ]])
}
summary(object = d)

test <- readRDS("data_test_sex.rds")
for ( v in c("sex", "tissue_status", "histology", "os_months", "dead", "dead_at_24_months", "t", "n", "m", "tnm_stage", "tnm_grade") ) {
    test[[ v ]] <- as.factor(x = test[[ v ]])
}
summary(object = test)

## PUT YOUR SCRIPT HERE
gs = names(d)[13:1012]
p_values = rep(NA, length(gs))
names(p_values) <- gs

for (i in 1:length(gs)) {
  model <- glm(
    formula = sex ~ d[, gs[i]],
    data = d,
    family = binomial(link = 'logit')
  )
  
  coeffs = summary(model)$coefficient
  if (nrow(coeffs) != 1) {
    p_values[i] = summary(model)$coefficient[2, 4]
  }
}

p_values_min = head(sort(p_values), n = 20)
genes_selected = paste(names(p_values_min), collapse = "+", sep = "")
form = paste("sex ~", genes_selected)

model <- glm(
  formula = as.formula(form),
  data = d,
  family = binomial(link = 'logit')
)
step(model, dir = "backward")

pred <- predict.glm(object = model, newdata = test, type = "response")
idx  <- pred <= 0.5
pred[  idx ] <- levels(x = d$sex)[ 1 ]
pred[ !idx ] <- levels(x = d$sex)[ 2 ]
table(pred, useNA = "ifany")

### DO NOT CHANGE THIS PART
saveRDS(pred, "results.rds")
zip_filename <- paste0(
    "results_"
  , format(x = Sys.time( ), format = "%Y_%m_%d_-_%s")
  , ".zip"
)
zip(zip_filename, "results.rds")
print(zip_filename)
```

## Submit zip file

It generates *`r zip_filename`* submission file.

Submit the zip submission file in the `Participate` tab of the codalab challenge by clicking the `Submit` button.

The metric used to evaluate prediction is the true positive rate (TPR) coded with the provided `scoring_function()`.

On the codalab challenge web page, The *STATUS* become : 

  - Submitting
  - Submitted	
  - Running
  - Finished

When it’s finished: 

  - You refresh the page and see you score in the column *TPR* 
  - Details for report could be downloaded by clicking *Download output from scoring step*.
  - Leader borad is updated in the `Results` tab.
