---
title: "Untitled"
author: "MARTHINET"
date: "20 janvier 2020"
output: html_document
---

```{r}
library(randomForest)
spectra_train <- read.csv2("C:/Users/im2ag/Desktop/DATA-CHALLENGE/spectra-train.csv", header = FALSE)
meta_train <- read.csv2("C:/Users/im2ag/Desktop/DATA-CHALLENGE/meta-train.csv")

spectra_test <- read.csv2("C:/Users/im2ag/Desktop/DATA-CHALLENGE/spectra-test.csv", header = FALSE)
meta_test <- read.csv2("C:/Users/im2ag/Desktop/DATA-CHALLENGE/meta-test.csv")

spectra_train <- apply(spectra_train, 2, as.numeric)
spectra_test <- apply(spectra_test, 2, as.numeric)

meta_train[,1] <- as.factor(as.numeric(gsub("sp_", "", as.character(meta_train[,1]))))
```


```{r}
var_spectres <- apply(spectra_train, 1, var)
plot(var_spectres)
var_souche <- tapply(var_spectres, rep(1:346, each = 9), mean)
plot(var_souche)
souche_outliers <- as.numeric(names(sort(var_souche, decreasing = TRUE)[1:3]))
individu_outliers <- which(meta_train[,2] %in% souche_outliers)
```


```{r}
library(FactoMineR)
res.pca <- PCA(spectra_train[-individu_outliers,], graph = FALSE)

barplot(res.pca$eig[1:20,2])

contrib_pp <- apply(res.pca$var$contrib[,1:2], 1, sum)
var_signif <- names(sort(contrib_pp, decreasing = TRUE)[1:100])
ind_var_signif <- as.numeric(gsub("V", "", var_signif))
sort(ind_var_signif)
```


```{r}
n <- nrow(spectra_train)
ind_ligne <- sample.int(n, floor(0.7*n))

X_train <- spectra_train[ind_ligne,]
X_test <- spectra_train[-ind_ligne,]
Y_train <- meta_train[ind_ligne,1]
Y_test <- meta_train[-ind_ligne,1]


### Avec variables significatives
model_signif <- randomForest(Y_train ~ ., data = X_train[,ind_var_signif], ntree = 500, na.action = na.omit)

hist(model_signif$oob.times)
plot(model_signif$importance)

pred <- as.numeric(as.vector(predict(model_signif, X_test)))
sum(pred == Y_test)/length(pred) 

### Avec tout
model_all <- randomForest(Y_train ~ ., data = X_train, ntree = 500, na.action = na.omit)

#hist(model$oob.times)
#plot(model_all$importance)

pred <- as.numeric(as.vector(predict(model_all, X_test)))
sum(pred == Y_test)/length(pred)

```
```{r}

library(randomForest)

model_all <- randomForest(Y_train ~ ., data = X_train, ntree = 500, na.action = na.omit)

pred <- as.numeric(as.vector(predict(model_all, X_test)))


#fonction d'évaluation
error_rate <- function(yobs,ypred){
 #matrice de confusion
 mc <- table(yobs,ypred)
 #taux d'erreur
 err <- 1.0 - sum(diag(mc))/sum(mc)
 return(err)
}


#erreur en test
print(error_rate(Y_test,pred))

#matrice de confusion out-of-bag
print(model_all$confusion)

#erreur out-of-bag
print(1-sum(diag(model_all$confusion))/sum(model_all$confusion))
```


```{r}
#accès au 1er arbre
#print(getTree(model_all,1))

#apparition des variables
print(data.frame(cbind(colnames(X_train)[2:20],varUsed(model_all))))

#importance des variables
b<-varImpPlot(model_all)

```
```{r}
#importance des variables
b<-varImpPlot(model_all)
var_imp<-sort(b,decreasing = TRUE)[1:43]
ind_var_imp<-which(b %in% var_imp)
 

model_sign <- randomForest(Y_train ~., data = X_train[,ind_var_imp], ntree = 500, na.action = na.omit,
      classwt = rep(1/42,42))

pred_imp <- as.numeric(as.vector(predict(model_sign, X_test)))
sum(pred_imp == Y_test)/length(pred_imp)

```

